# wrangler.toml

name = "nice-mee" # Choose a unique name for your worker
compatibility_date = "2025-06-22"

# This section tells the Worker where to find your static files.
# It replaces the "Build output directory" setting.
[site]
bucket = "./public"

# This section defines the build command that Wrangler
# will run before deploying. It replaces the "Build command" setting.
[build]
command = "npx quartz build"